egov-searcher/localitySearcher.yml
locality searcher for NOC.
As of now NOC is for BPA, so fetching the locality from the bpa
=> locality searcher for NOC

pdf-service/data-config/ws-onetime-receipt.json
WOR-393 In the receipt pdf Balance bill amount is coming in negative
=> WOR-393 In the receipt pdf Balance bill amount is coming in negative

egov-searcher/localitySearcher.yml
OAP-624 - locality yaml issue fixed
=> OAP-624 - locality yaml issue fixed

pdf-service/data-config/ws-onetime-receipt.json
WOR-393 Pending amount value shows in negative
=> WOR-393: Pending amount value shows in negative

pdf-service/format-config/ws-bill.json
WOR-409 bill alignment  modification is  fixed
=> WOR-409 bill alignment  modification is  fixed

pdf-service/format-config/ws-bill.json
RAIN-1332 bill alignment modification is fixed
=>    RAIN-1332 bill alignment modification is fixed

pdf-service/format-config/ws-bill.json
=> WOR-403 Bill format changes

pdf-service/data-config/ws-bill.json, pdf-service/format-config/ws-bill.json
WOR-403 roundoff adjusted amount and other amount value upto two decimal and fixed alignment issue
=> WOR-403 roundoff adjusted amount and other amount value upto two decimal and fixed alignment issue

pdf-service/data-config/ws-bill.json
WOR-403 W&S: Bill format changes
=> WOR-403 W&S: Bill format changes

pdf-service/data-config/ws-bill.json
WOR-403 : Corrected the tenant id for the WS bills
=> WOR-403 : Corrected the tenant id for the WS bills

pdf-service/data-config/ws-bill.json
WOR-403 : Rondoff issue in advance adjusted
=> WOR-403 : Rondoff issue in advance adjusted

pdf-service/format-config/ws-bill.json
WOR-403 - ws bill format changes and removed page break
=> WOR-403 - ws bill format changes and removed page break

pdf-service/format-config/ws-estimationnotice.json
WOR-426 Change in estimate notice pdf format
=> WOR-426 Change in estimate notice pdf format

egov-persister/apportion-persister.yml
RAIN-1448 - Updated for Apportion Audit fix
=> RAIN-1448 - Updated apportion persister for Apportion Audit fix

reports/config/pgr-reports.yml
RAIN-1379 :: Search param changes for PGR reports
=> RAIN-1379 :: Search param changes for PGR reports

egov-persister/property-services-registry.yml
=> RAIN-1583: Update property-services-registry.yml

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
[RAIN-1594]
Fixes count mismatch for high level and low level drilldowns.
[RAIN-1594]: https://digit-discuss.atlassian.net/browse/RAIN-1594
=> [RAIN-1596]

reports/configs/pgr-reports.yml
RAIN-1605: migrate the configs - uat PGR Reports
=>  RAIN-1605: migrate the configs - uat PGR Reports

egov-searcher/localitySearcher.yml
RAIN-1605 - Updated searcher query for W&S in QA
=> RAIN-1605 - Updated searcher query for W&S in QA

egov-searcher/localitySearcher.yml
RAIN-1605 - Updated searcher query for W&S in UAT
=> RAIN-1605 - Updated searcher query for W&S in UAT

egov-persister/water-persist.yml
RAIN-1660 - Added isoldApplication flag in eg_ws_connection
=> RAIN-1660 -Added isoldApplication eg_ws_connection

egov-persister/sewerage-persist.yml
RAIN-1660 - Added isoldApplication flag in eg_sw_connection
=> RAIN-1660 -Added isoldApplication eg_sw_connection

reports/config/pgr-reports.yml
RAIN-1660 - Column order changes in PGR Reports
=> RAIN-1660 - Column order changes in PGR Reports

reports/config/pgr-reports.yml
RAIN-1660: Change in column order for ULB and Description Report
=> RAIN-1660: Change in col order-ULB & Desc report

egov-searcher/bill-genie.yml
Reverts egovernments/configs#575
=> Revert "RAIN-1887: Minor change in PT bill search"

egov-persister/hrms-employee-persister.yml
Added eg_hrms_reactivationdetails table in hrms config
=> RAIN-1660 Added eg_hrms_reactivationdetails

pdf-service/data-config/buildingpermit-low.json, pdf-service/data-config/buildingpermit.json
Update module code in the collection search end-point
=> OAP-645 Update collection URL in the permit order

pdf-service/data-config/buildingpermit-low.json, pdf-service/data-config/buildingpermit.json
OAP-645 Update collection search URL in the building permit order
=> OAP-645 Update collection search URL in the building permit order

egov-indexer/chatbot-telemetry-v2.yaml
Added chatbot-telemetry-v2 file
=> RAIN-2164 :: Added chatbot-telemetry-v2 file

egov-persister/fsm-persister.yaml
RAIN-2164 Added fsm persister.yaml file
=> RAIN-2164 Added fsm persister.yaml file

reports/config/employee-report.yml
=> RAIN-2164 Employee status key value pairs

reports/config/employee-report.yml
Fixes search result not being displayed when searching by role
=> RAIN-2164 - Changes for Employee search by role

egov-persister/fsm-calculator-persister.yaml
RAIN-2164 Added fsm calculator persister.yaml file
=> RAIN-2164 Added fsm-calculator-persister.yaml file

egov-persister/vehicle-persister.yaml
RAIN-2164 Updated Vehicle Persister Details
=> RAIN-2164 Updated Vehicle Persister Details

egov-persister/fsm-persister.yaml
RAIN-2164 Updated fsm-persister.yaml file
=> RAIN-2164 Updated fsm-persister.yaml file

egov-persister/fsm-persister.yaml
=> RAIN-2164 - Updated fsm persister according

pdf-service/format-config/bill-amendment-note.json
Format Config changes for note generation text dynamic
=> RAIN-2164 Format Config changes

egov-indexer/egov-fsm.yaml
=> RAIN-2164 Added Indexer file

egov-indexer/egov-fsm.yml
RAIN-2164 Added Indexer Details
=> RAIN-2164 Added Indexer Details

egov-persister/vehicle-persister.yaml
RAIN-2164 Added Vehicle Persister details
=> RAIN-2164 Added Vehicle Persister details

egov-persister/vendor-persister.yaml
RAIN-2164 Added vendor persister details
=> RAIN-2164 Added vendor persister details

egov-indexer/egov-vendor.yaml
RAIN-2164 Added vendor.yaml file
=> RAIN-2164 Added vendor.yaml file

pdf-service/data-config/fsm-receipt.json
RAIN-2164 Updated Receipt Details
=> RAIN-2164 Updated Receipt Details

pdf-service/format-config/fsm-receipt.json
RAIN-2164 Updated format details
=> RAIN-2164 Updated format details

reports/config/employee-report.yml
=> RAIN-2164 Filtered out Citizen entry in employee

pdf-service/data-config/sewarage-bill-amendment-note.json
Created Sewarage-Bill-Amendment.json file for Bill Amendment bug fix for this issue RAIN-2299
=> RAIN-2164 Created Sewarage-Bill-Amendment.json

pdf-service/format-config/sewerage-bill-amendment-note.json
Created sewerage-bill-amendment-note.json file for Bill Amendment bug fix for this issue RAIN-2299
=> RAIN-2164 Created sewerage-bill-amendment-note

pdf-service/data-config/sewarage-bill-amendment-note.json
Modified sewerage-bill-amendment-note.json file
=> RAIN-2164 Modified sewerage-bill-amendment-note

reports/config/employee-report.yml
=> RAIN-2164 Updated list of employees in search

reports/config/employee-report.yml
default to pb to show all roles
=> RAIN-2164 Changed the mdms roles folder from

egov-persister/fsm-persister.yaml
Updated SlumName related query & json path
=> RAIN-2164 Updated SlumName query & json path

reports/config/employee-report.yml
=> RAIN-2164 - Employee Report Fixes user roles not

reports/reportFileLocationsv1.txt
file path to report location file
=> RAIN-2164 - Added HRMS employee report config

pdf-service/data-config/fsm-receipt.json
=> RAIN-2164 Updated line no 480 ad 517

egov-indexer/chatbot-telemetry-v2.yaml
=> RAIN-2164 Added chatbot telemetry v2 file

reports/config/employee-report.yml
=> Rain-2164 Updated employee report

reports/config/employee-report.yml
=> RAIN-2164 Updated employee report to

reports/config/pgr-reports.yml
in GRO and LME performance report
=> RAIN-2164 Fixes employee name being shown as NULL

egov-searcher/localitySearcher.yml
fixed locality search space issue
=> fixed locality search space issue

pdf-service/format-config/fsm-receipt.json
FSM-receipt appli NO falls into two lines fixed
=> FSM-receipt appli NO falls into two lines

egov-persister/fsm-persister.yaml
RAIN-2164 Updated persister details
=> RAIN-2164 Updated persister details

egov-persister/egov-workflow-v2-persister.yml
=> RAIN-2164 Added #10 & #45 for rating

egov-persister/egov-workflow-v2-persister.yml
=> RAIN-2164 Added #10 and #45 for rating

egov-indexer/egov-fsm.yaml
FSM indexer update by adding collection, workflow and other services
=> Update for fsm indexer by adding collection, workflow and other services

pdf-service/format-config/fsm-receipt.json
=> removing municpal corporation

pdf-service/data-config/fsm-receipt.json, pdf-service/format-config/fsm-receipt.json
=> FSM receipt issue fixed

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
=> FSM-293 Sure Dashboard

egov-indexer/egov-fsm.yml
=> fsm index updated

egov-indexer/egov-fsm.yml
additional Details chanes reverted
=> FSM-DSS-DEMO

reports/config/fsm-reports.yml
Data issue in Desludging Report
=> RAIN-2768 Data issue in Desludging Report

reports/config/fsm-reports.yml
Updated data issue for Desluding report
=> RAIN-2768 Updated data issue for Desluding report

reports/config/fsm-reports.yml
Updated FSTP name list for Vehicle log report
=> RAIN-2768 Updated FSTP name list

egov-searcher/inboxpropertysearch.yml
Reverts egovernments/configs#1013
=> Revert "[RAIN-2992] Added assignee as search criteria in PT inbox searcher co…"

egov-searcher/inboxpropertysearch.yml
Updated inbox property search for assignee param
=> RAIN-2768 Updated inbox property search

egov-searcher/inboxpropertysearch.yml
Changed INNER JOIN to LEFT JOIN for process table
=> RAIN-2768 Changed INNER JOIN to LEFT JOIN

pdf-service/data-config/tlcertificate.json, pdf-service/format-config/tlcertificate.json
Reverts egovernments/configs#1022
=> Revert "[RAIN-2830] Added QR code functionality in TL Certificate config and aligned it to the right"

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-2768 : Added FSM DSS configurations
=> RAIN-2768 : Added FSM DSS configurations

egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
RAIN-2768 : added id : fsm, id : ulb-fsm
=> RAIN-2768 : added id : fsm, id : ulb-fsm

reports/config/pt-reports.yml
=> RAIN-2768 Added active owner condition to show

egov-searcher/inboxTLSearch.yml
=> RAIN-2768 Updated TL searcher config

reports/config/pt-reports.yml
=> RAIN-2768 corrected the duplicate owner issue

egov-searcher/inboxTLSearch.yml
Reverts egovernments/configs#1071
=> Revert "RAIN-2768 Updated TL searcher for sort issue"

reports/config/fsm-reports.yml
Updated report config for Status dropdown
=> RAIN-2768 Updated report config for Status dropdow

reports/config/fsm-reports.yml
=> RAIN-2768 Updated config for fsm report

egov-indexer/egov-url-shortening-indexer.yaml
=> RAIN-3414 Added indexer config for url shortening

egov-searcher/inboxBPASearch.yml
Added application and service type search filter
=> RAIN-3414 Added application and service type

egov-searcher/bill-genie.yml
Corrected malformed mcollect bills query
=> RAIN-3414 Corrected malformed mcollect bills query

egov-indexer/fire-noc-service.yml
=> Added firenoc indexer config file

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
rain-4610 and 4604update of target achieved
=> rain-4610 and 4604update of target achieved

egov-indexer/fire-noc-service.yml
added channel field - RAIN-4652
=> added channel field - RAIN-4652

egov-indexer/fire-noc-service.yml
added isBulk property- RAIN-4651
=> added isBulk property- RAIN-4651

egov-indexer/fire-noc-service.yml
indexmapping missmatch - RAIN-4651
=> indexmapping missmatch - RAIN-4651

egov-indexer/fire-noc-service.yml
wrong indexmapping - RAIN-4651
=> wrong indexmapping - RAIN-4651

egov-indexer/fire-noc-service.yml
Exception for assignee - RAIN-4651
=> Exception for assignee - RAIN-4651

egov-indexer/fire-noc-service.yml
Exception for $['fireNOCDetails']['auditDetails'] - RAIN-4651
=> Exception for $['fireNOCDetails']['auditDetails'] - RAIN-4651

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
fire noc dashboard - RAIN-4651 and RAIN-4652
=> fire noc dashboard - RAIN-4651 and RAIN-4652

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
index name mismatch - RAIN-4651
=> index name mismatch - RAIN-4651

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
=> RAIN-4651 update

egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
Added id in roleDashboard -RAIN-4651
=> Added id in roleDashboard -RAIN-4651

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
fireno in home dashboard RAIN-4651
=> fireno in home dashboard RAIN-4651

egov-indexer/sewerage-service.yml, egov-indexer/water-service.yml
water-service.yml and sewerage-service.yml updated
=> W&S- Indexer update for-water-service and sewerage-service

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
W&S: DSS: Revenue - Top and Bottom Performing ULBs
=> [RAIN-4610]-W&S: DSS: Revenue - Top and Bottom Performing ULBs

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
[RAIN-4604] W&S: DSS: Revenue - Overview Card- Today's, total,target collection and target achieved.
[RAIN-4604]: https://digit-discuss.atlassian.net/browse/RAIN-4604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RAIN-4604]Todays,total,target collection and target achieved

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
=> BPA changes removed

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Fire-noc pie chart issue RAIN-4651
=> Fire-noc pie chart issue RAIN-4651

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Service report for fire-noc RAIN-4654
=> Service report for fire-noc RAIN-4654

egov-indexer/fire-noc-service.yml
Fire noc indexer update RAIN-4654
=> Fire noc indexer update RAIN-4654

egov-indexer/fire-noc-service.yml
Missed adding firestationId RAIN-4654
=> Missed adding firestationId RAIN-4654

egov-indexer/fire-noc-service.yml
Added query param for localization RAIN-4654
=> Added query param for localization RAIN-4654

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json, egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json, egov-indexer/fire-noc-service.yml
fire-noc indexer and tickets RAIN-4651,RAIN-4652,RAIN-4654
=> fire-noc indexer and tickets RAIN-4651,RAIN-4652,RAIN-4654

egov-indexer/fire-noc-service.yml
Rain-4654 service report issue
=> Rain-4654 service report issue

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-ingest/transform_firenoc_v1.json, egov-indexer/fire-noc-service.yml
=> Rain 4654 Table chart

egov-persister/fsm-persister.yaml
fsm indexer not updated properly
=> fsm indexer not updated properly

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
RAIN-4654 total collection issue
=> RAIN-4654 total collection issue

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Reverts egovernments/configs#1318
=> Revert "Ws qa"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json, egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
NSS fire noc - RAIN-5015,Rain-5016
=> NSS fire noc - RAIN-5015,Rain-5016

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
RAIN-4654 changed number to amount for total collection
=> RAIN-4654 changed number to amount for total collection

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Reverts egovernments/configs#1348
=> Revert "[RAIN-4616]-ws connection ageing card"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Reverts egovernments/configs#1351
=> Revert "[RAIN-4612]-ws key financial indicators"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Reverts egovernments/configs#1357
=> Revert "RAIN-4612-ws financial update2"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Reverts egovernments/configs#1359
=> Revert "[RAIN-4612]-ws financial key indicators update 3"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Reverts egovernments/configs#1361
=> Revert "[RAIN-4612]-ws financial key indicators update 4"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Reverts egovernments/configs#1363
=> Revert "[RAIN-4612]-ws financial key indicators update 5"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-indexer/fire-noc-service.yml
=> RAIN-4654 drilldown added

egov-indexer/water-service.yml
Reverts egovernments/configs#1394
=> Revert "Indexer update"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
=> RAIN-5128,Rain-5129

egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
=> Added role config for firenoc

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
=> RAIN-5130,RAIN-5131

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Prefixes are not properly added for localization codes - RAIN-5199
=> Prefixes are not properly added for localization codes - RAIN-5199

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
FireNoc Tab-bottom 3 states based on noc issued-RAIN-5132
=> FireNoc Tab-bottom 3 states based on noc issued-RAIN-5132

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Reverts egovernments/configs#1460
=> Revert "[RAIN-5090]- National Dashboard-WS Taxhead"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Added insights for overview card - RAIN-5100
=> Added insights for overview card - RAIN-5100

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
=> RAIN-5133 service report

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
service report issue with department RAIN-5133
=> service report issue with department RAIN-5133

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
=> insights changes RAIN-5133

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
RAIN-5133 service report chart
=> RAIN-5133 service report chart

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Todays Collection metric for WS
=> [RAIN-5014]-NSS WS Todays Collection

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
RAIN-5133 service report changes
=> RAIN-5133 service report changes

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
RAIN-5199 No Data is displayed for Department Service Report
=> RAIN-5199 No Data is displayed for Department Service Report

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Reverts egovernments/configs#1497
=> Revert "[RAIN-4607]-DSS-WS-Service Overview card-total connections"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json, egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
Added firenoc changes for national dashboard RAIN-4675
=> Added firenoc changes for national dashboard RAIN-4675

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5011-nss_ws_target_achieved
RAIN-5012-nss_ws_target_collection
=> NSS W&S Target Collection and Target Achievement

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
missed commits for firenoc RAIN-4675
=> missed commits for firenoc RAIN-4675

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
=> fire-noc changes from dev

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5133 Changed service report tab from state to region
=> RAIN-5133 Changed service report tab from state to region

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5355,RAIN-5358 Service report and pie chart by type
=> RAIN-5355,RAIN-5358 Service report and pie chart by type

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Rain 5284: National Dashboard Landing Page Configuration
=> Rain 5284: National Dashboard Landing Page Configuration

egov-persister/fsm-persister.yaml
Reverts egovernments/configs#1554
=> Revert "SAN-818_vehicle capacity instead of vehicle make"

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
=> SLA compliance issue fix

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Updated Today's collection and cumulative collection query
=> 4604- State dss-ws-Updated Today's collection and cumulative collection query

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Performance matrics for fire noc aggregation path changes
=> Performance matrics for fire noc aggregation path changes

egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
RAIN-5824: rolemapping for Landing page National Dashboard
=> RAIN-5824: rolemapping for Landing page National Dashboard

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5430, RAIN-5476 firenoc bug fixes
=> RAIN-5430, RAIN-5476 firenoc bug fixes

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5476, RAIN-5467 firenoc service report and overview
=> RAIN-5476, RAIN-5467 firenoc service report and overview

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5476 The Revenue tab is displayed on Firenoc
=> RAIN-5476 The Revenue tab is displayed on Firenoc

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5202, RAIN-5430 Data in the Overview card is not filtering
=> RAIN-5202, RAIN-5430 Data in the Overview card is not filtering

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
=> Issue with ULB drilldown

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN-5430 line charts one blow other dividing overview into revenue
=> RAIN-5430 line charts one blow other dividing overview into revenue

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
RAIN-5202 Overview card is not filtering when State is added
=> RAIN-5202 Overview card is not filtering when State is added

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
insight for today's collection changes comparision from month to year.
=> fix for rain-5701

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
RAIN-5712 Todays Collection changes
=> RAIN-5712 Todays Collection changes

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
module wise liveulb query fixed
=> module wise liveulb query fixed

egov-persister/fsm-persister.yaml
Making changes as part of sprint 4 stories
=> Making changes as part of sprint 4 stories

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
#RAIN-6334 The Total Collection is shown as 0
=> #RAIN-6334 The Total Collection is shown as 0

egov-persister/vehicle-persister.yaml
=> Updated vehicle trip changes

egov-persister/vehicle-persister.yaml
FSM - Removed vehicledeclinereason  fields due to trip scheduling issue
=> FSM - Removed vehicledeclinereason  fields due to trip scheduling issue

egov-persister/vehicle-persister.yaml
FSM-Vehicle TRIP issue resolution
=> FSM-Vehicle TRIP issue resolution

egov-indexer/sewerage-service.yml
Reverting changes forsewerage indexer
=> RAIN-4911 Reverting changes for sewerage indexer

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
SAN-932 - FSM - DSS Dashboard changes
=> SAN-932 - FSM - DSS Dashboard changes- MasterDashboardConfig.json

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
=> Map states more than 10

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
SAN-932 - FSM -Dashboard changes
=> SAN-932 - FSM -Dashboard changes

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Added module specific localization code for revenue and overview
=> RAIN-4911 Added module specific localization code

egov-persister/echallan.yml
Updated echallan query for receipt no
=> RAIN-4911 Updated echallan query for receipt no

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
`RAIN: 6570` Birth and Death National Dashboard Configs
=> RAIN: 6570 Birth and Death National Dashboard ChartAPI configs

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
`RAIN: 6570` Birth and Death National Dashboard master API ID value changed
=> RAIN: 6570 Birth and Death National Dashboard master API ID value changed

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
RAIN: 6570 Birth and Death National Dashboard: fixed DSS dummy value was displaying in UI
=> RAIN: 6570 Birth and Death National Dashboard DSS data was populating

egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
RAIN-6570: Update RoleDashboardMappingsConf.json
=> RAIN-6570: Update RoleDashboardMappingsConf.json

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
id value changed for BnD chart config
=> RAIN:6570 Update MasterDashboardConfig.json

egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
Updated the id value pair for nss BND
=> RAIN:6570 Update RoleDashboardMappingsConf.json

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Queries are modified as per the changes suggested.
=> RAIN: 6570 Birth and Death National Dashboard queries changed

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
update the config changes for dev
=> RAIN:6570 Updates in the chartAPIconfigs.json

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Updated the changes from dev to qa branch
=> RAIN: 6570 Updates ChartApiConfig.json as per DEV

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Some indentation was repeated several times, have removed that.
=> RAIN-6570:  Update ChartApiConfig.json

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
updated the config for requested filter
=> RAIN-6570: Update ChartApiConfig.json

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Added drill down for age category for death
=> RAIN:6570 Update ChartApiConfig.json

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Added overview page configs for birth and death national dss
=> RAIN:6763 Update ChartApiConfig.json

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Added Landing page config for birth and death national dss
=> 6763: Update MasterDashboardConfig.json

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Merged both the config cards data for BND
=> RAIN: 6763 Update MasterDashboardConfig.json

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
removed birth card from landing page
=> RAIN-6763 Update MasterDashboardConfig.json removed birth card

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Updated the module name for birth and death cards on overview
=> RAIN-6763 Update ChartApiConfig.json

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
removed date reference field from total collection overview page-BND module
=> RAIN-6763 Update ChartApiConfig.json removed date reference field

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
National Dashboard : Landing Page : The % values and collection values as whole numbers in the landing page for BND module
=> RAIN-6496 Update ChartApiConfig.json:  Landing Page : The % values and collection values as whole numbers in the landing pag

egov-persister/vendor-persister.yaml
SAN-1047 - Vendor update changes
=> SAN-1047 - Vendor update changes-vendor-persister.yaml

egov-persister/vehicle-persister.yaml
SAN-1047 - Vendor update changes-vehicle-persister.yaml
=> SAN-1047 - Vendor update changes-vehicle-persister.yaml

pdf-service/data-config/birth-certificate-pdf.json
Change Government of City A → Government of </state name> in both Birth & Death Certificates
=> RAIN-7127 : Update birth-certificate-pdf.json

pdf-service/data-config/birth-certificate-pdf.json
Reverts egovernments/configs#2099
=> Revert "RAIN-7127 : Update birth-certificate-pdf.json"

egov-persister/egov-survey-service-persister.yml
according to the order in which they are ingested
=> RAIN-6821 Config to preserve questions order

egov-indexer/egov-vehicle.yaml
SAN-1088 - Dashboard prod issue - Part 3
=> SAN-1188 - Dashboard prod issue - Part 3

egov-indexer/egov-vehicle.yaml
SAN-1088 fsm externalurmapping issue fixed
=> SAN-1088 fsm externalurmapping issue fixed

egov-indexer/egov-vehicle.yaml
SAN-1088 fsm externalurmapping issue fixed
=> SAN-1188 fsm externalurmapping issue fixed- Dashboard prod 

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
SAN-1089 an SAN-1188 data not found issue
=> SAN-1089 an SAN-1188 data not found issue

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
SAN-1089 and SAN-1188 vehicle chart data resolved
=> SAN-1089 and SAN-1188 vehicle chart data resolved

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
SAN-1089 Dashboard issue for vehicle log report
=> SAN-1089 Dashboard issue for vehicle log report

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
SAN-1089 Data not available issues
=> SAN-1089 Data not available issues

egov-indexer/egov-vehicle.yaml
=> SAN-1089 modified accordingly

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
SAN-1188 - Dashboard prod issue- customer rsting
=> SAN-1188 - Dashboard prod issue- customer rsting

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
SAN-1188 dashboard data for Capacity Utilization and Customer Rating
=> SAN-1188 dashboard data for Capacity Utilization and Customer Rating

egov-persister/vendor-persister.yaml
=> SM-511-Driver tab changes in qa 

egov-persister/vendor-persister.yaml
SM-766 Not able to change the vendor in driver details.
=> SM-766 Not able to change the vendor in driver details.

egov-persister/vendor-persister.yaml
SM-801 Not able to create vendor in UAT using api
=> SM-801 Not able to create vendor in UAT using api

egov-persister/vehicle-persister.yaml
SM-801 removing extra tab space
=> SM-801 removing extra tab space

egov-persister/vehicle-persister.yaml
=> SM-801 correcting indentation

egov-persister/vehicle-persister.yaml
SM-801 vehicle not able to create in uat
=> SM-801 vehicle not able to create in uat

reports/config/birthcount-reports.yml
Updated  changes in Birth count reports
=> UM-464: Updated  changes in Birth count reports

egov-searcher/inboxBillAmendmentWsSearch.yml
Added file inboxBillAmendmentWsSearch.yml
=> Added file inboxBillAmendmentWsSearch.yml file

reports/config/birthcount-reports.yml
Changed the name to name on certificate
=> UM-4902 Changed the name to name on certificate

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Removed target collection from TL Dss
=> Um-4763 :: TLcartApichange

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Removed target collection from PT dss
=> um-4763 :: PtChartPiChnages

egov-indexer/privacy-audit.yaml
=> um-4763 :: PrivacyAudit

egov-dss-dashboards/dashboard-analytics/RoleDashboardMappingsConf.json
=> UM-5160 :: Finance Config updated

egov-persister/audit-service-persister.yml, egov-persister/bulk-bill-generator-sw.yml, egov-persister/bulk-bill-generator-ws.yml
Added files as follows : audit-service-persister.yml
bulk-bill-generator-sw.yml
bulk-bill-generator-ws.yml
=> um-4763 :: PersisterFileAdded

reports/reportFileLocationsv1.txt
=> um-4763 :: TL Obps Report Added

reports/config/rainmaker-tl-reports.yml
deleted duplicate code and extra added footer which is not in qa due to this extra lines getting Error in retrieving report definition
=> um-4763 - tlreportschanges

reports/config/rainmaker-wns-reports.yml
=> [UM-5202]- Update searchParam and query for giving support for new applications

reports/config/pt-reports.yml
Pt report collection report bug fix.
=> UM-5178 : Pt Report Bug fix Updated the query

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
=> UM-5121,UM-5120,UM-4694 DSS new KPI

egov-indexer/property-services.yml
=> [UM-5579]- Added property fuzzy search topic and index in property-services

reports/config/rainmaker-obps-reports.yml
=> Adding isLocalisationRequired as true

egov-persister/fsm-persister.yaml, pdf-service/data-config/fsm-receipt.json, pdf-service/format-config/fsm-receipt.json
#SM-1902 Code migration from qa to uat
=> #SM-1902 config Code migration from qa to uat

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
Reverts egovernments/configs#2583
=> Revert "Removed insight"

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
Reverts egovernments/configs#2585
=> Revert "Removed slaachieved"

egov-persister/boundary-persister.yml
Added persister config for boundary - service
=> Boundary service persister

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json
=> changed the code of first row name like INPUT , TREATMENT QUALITY AND ALERTS #SM-3252

egov-persister/boundary-persister.yml
Added persister configs for boundary-relations create and update
=> [DPG-1993] Added boundary service persister configs

egov-persister/vendor-persister.yaml
sanitation worker persister changes
=> SM-3199: added persister changes for vendor sanitation worker

egov-indexer/sample-indexer.yml
testing indexer against elastic 8
=> qa-indexer-testing-v8

egov-indexer/sample-indexer.yml
testing indexer against new upgraded elastic version
=> indexer-testing

egov-indexer/sample.yml
testing indexer against elastic 8 version
=> indexer-testing-poc

egov-indexer/sample.yml
added sample yml file for testing
=> sample-yml-file-for-testing

health/egov-persister/project-factory-persister.yml
…g_resource_details and eg_resource_activity tables in QA
=>  persister configuration to enable the persistence of data into the tables

health/egov-persister/facility-persister.yml, health/egov-persister/household-persister.yml, health/egov-persister/individual-persister.yml, health/egov-persister/product-persister.yml, health/egov-persister/project-persister.yml, health/egov-persister/project-task-persister.yml, health/egov-persister/referral-management-persister.yml, health/egov-persister/stock-persister.yml
Changes made in persister files of health services to accomodate for the changes made to data being sent to kafka in the respective services
=> HLM-5030 persister changes for kafka

health/egov-persister/facility-persister.yml, health/egov-persister/household-persister.yml, health/egov-persister/individual-persister.yml, health/egov-persister/product-persister.yml, health/egov-persister/project-persister.yml, health/egov-persister/project-task-persister.yml, health/egov-persister/referral-management-persister.yml, health/egov-persister/stock-persister.yml
Reverts egovernments/configs#3023
=> Revert "userUuidJsonPath changed to take user uuid from userInfo in RequestInfo"

egov-persister/sunbirdrc-credential-persister.yml
persister configuration for unified dev deployment of sunbirdrc credential service
=> persister configuration sunbirdrc

egov-persister/sunbirdrc-credential-persister.yml
=> persister name refactoring

egov-persister/rate-analysis-service-persister.yml
=> Added persiter config

egov-persister/tenant-manegement.yml
Added persister config for tenant management
=> Added persister config for tenant management

works/egov-indexer/mukta-pi-indexer.yml
Created mukta-pi-indexer.yml in unified qa as per promotion doc.
=> Created mukta-pi-indexer.yml in unified qa as per promotion doc.

health/egov-indexer/project-indexer.yml
project-indexer
Last modified, last modified by to createdTime and createdBy
=> Changed project-indexer fields

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
This reverts commit af1f4ec5be6ffa92e8da42e11118a7043e89f113.
=> Revert "Updated insights for required overview charts (#3266)"

health/egov-indexer/referral-management-indexer.yml, health/egov-indexer/service-request-indexer.yml
added indexer config for the following indexes:
1. referral-index-v1
2. side-effect-index-v1
3. hf-referral-index-v1
4. hf-referral-service-task-v1
=> added indexer config for referral flow

egov-persister/tenant-management.yml
Reverts egovernments/configs#3355
=> Revert "Update tenant-management.yml"

egov-persister/service-request-persister.yml
Reverts egovernments/configs#3381
=> Revert "Service definition update config added"

health/egov-persister/plan-service-persister.yml
Removed campaignId from planConfig update and added hierarchyLevel in planEmployeeAssignment create and update
=> Removed campaignId from plan config update 

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, health/egov-indexer/Plan-service-indexer.yml, health/egov-indexer/census-service-indexer.yml, health/egov-persister/census-service-persister.yml, health/egov-persister/plan-service-persister.yml
changes for microplan promotions
=> config changes for microplan promotions

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json, egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json, health/egov-persister/service-request-persister.yml
- Fixed population to children typo and supervisor checklists charts
- Revert "changed additionalDetails to additionalFields (3454)
=> Unified qa hcmpre 1330 7

health/egov-persister/plan-service-persister.yml
=> changes in persister

health/egov-persister/attendance-service-persister.yml, health/egov-persister/expense-bill-payment-persister.yml, health/egov-persister/muster-service-persister.yml, pdf-service/data-config/health-bill-payment.json, pdf-service/format-config/health-bill-payment.json
All the payment related config changes are here.
=> All the payments related config changes
